import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sider from "./components/Sider";
import { dbConfig } from "@/utils/dbConfig";
import { GlobalProvider } from "./global/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex gap-2">
            <Sider />
            <div className="w-full min-h-[97vh] m-2 border rounded-md p-3">
              {children}
            </div>
          </div>
        </body>
      </html>
    </GlobalProvider>
  );
}
